### PR TITLE
Create Project Outline

### LINKED ISSUE #1: Project Outline
Defining a project outline will be very helpful in guiding us as we start with development.

### PR DESCRIPTION
**Pull request by kaylendog**
This PR creates `0001-project-outline.md`, the document outlining how we will proceed with development.

### CODE REVIEW

**Review by JWFitzpatrick — APPROVED** [review]
Looks good

**Comment by actuallylost** [comment]
Looks good to me

**Review by actuallylost — APPROVED** [review]
Looks good to me!

**Review by jcxldn — APPROVED** [review]
LGTM. Thank you very much!

**Pull request merged**
